### ISSUE TITLE
ORBAT: Unit Text21 datatype

### ISSUE THREAD

**Issue by bergtwvd** [MSG134/NETN_FOM#10]
Why this specific restriction (21 chars) in the datatype? I would make it variable.
Also a different datatype name might be better: e.g. DesignationType.

So, UniqueDesignation and HigherFormation are of type DesignationType.

**Comment by LennartOlsson** [comment]
It is specified to be max 21 characters in MSDL (msdl:text21).

**Comment by bergtwvd** [comment]
I don't think we want to be constrained by the MSDL schema limits ?

**Comment by LennartOlsson** [comment]
This constraint and others are from MIL-STD 2525 C and APP 6.

In my opinion it should possible to import an ORBAT from a MSDL file and exported it to a MSDL file.
Changing data types will ruin or make it difficult to have this functionality.   

We can make extension but not change any existing definitions.

**Comment by LennartOlsson** [comment]
A Federate/Application that publish the ORBAT information in a Federation Execution must first load an ORBAT during the Federation Initialization and then save the ORBAT between Federation Executions, I do not know any better than using the SISO standard MSDL (SISO-STD-007-2008) for this. MSDL is used by many Federates/Applications in this community.

With this follows some constraints, definitions of attributes on object classes, definitions of data types, etc.

**Comment by bergtwvd** [comment]
Ok, so a design choice to remain compatible with MSDL and inherit these restrictions?

**Comment by bergtwvd** [comment]
One other question / remark: Datatype Test21 is 21 chars, but the SIDC is 15 chars. Why this different?
And if we expect a SIDC here, why not using a datatype name such as ``SIDC``?

**Comment by LennartOlsson** [comment]
These data types is for different types of attributes, the name of the data type for SIDC is SymbolIdentifierArray15 defining a character sequence of exactly 15 chars, 
Data type Text21 is a character sequence with 0-21 chars.

**Comment by LennartOlsson** [comment]
These data types is for different types of attributes, the name of the data type for SIDC is SymbolIdentifierArray15 defining a character sequence of exactly 15 chars,
Data type Text21 is a character sequence with 0-21 chars.
