### ISSUE TITLE
ORBAT: interaction classes

### ISSUE THREAD

**Issue by bergtwvd** [MSG134/NETN_FOM#12]
I propose to remove these.

The string value can be quite large.

**Comment by LennartOlsson** [comment]
Yes, could be removed if no one sees any use of them.

**Comment by bergtwvd** [comment]
Ok, once thsi is processed in a next commit, the issue can be closed.

**Comment by LennartOlsson** [comment]
I will remove these interaction classes in the next version of the FOM module.
