### ISSUE TITLE
ORBAT: federate names or federateType names

### ISSUE THREAD

**Issue by bergtwvd** [MSG134/NETN_FOM#4]
Federate name is too specific, as it changes per run even. Better is to use federateType name.

**Comment by LennartOlsson** [comment]
Federate name does not change during a federation execution and is unique during the federation execution.

Federate type is not unique in a federation execution.

**Comment by bergtwvd** [comment]
Yes, federate name is ok. I assume that the federate that creates the object instance will have sorted out the proper name to use.

**Comment by LennartOlsson** [comment]
No changes will be done according to this.
