### ISSUE TITLE
ORBAT: Federate as subclass of OrbatObject

### ISSUE THREAD

**Issue by bergtwvd** [MSG134/NETN_FOM#5]
Is it logical to have the Federate class as subclass of OrbatObject? A federate is not an OrbatObject. In that case it should be under the root or some other top-level class.

**Comment by LennartOlsson** [comment]
It is a part in the MSDL schema, with the common attributes Name and UUID as i the object classes OrbatObject.Unit and OrbatObject.Force.

Can be moved to the HLAobjectRoot.

**Comment by bergtwvd** [comment]
Ok then.

**Comment by LennartOlsson** [comment]
I will move the Federate object class to HLAobjectRoot in the next version.

**Comment by LennartOlsson** [comment]
I will move the Federate object class to HLAobjectRoot in the next version.
