### ISSUE TITLE
ORBAT: Unit.Force attribute

### ISSUE THREAD

**Issue by bergtwvd** [MSG134/NETN_FOM#7]
Does the attribute value refer to a Force object instance?  This is not clear from the semantics.

**Comment by LennartOlsson** [comment]
Yes, the Force is identified by its UUID (datatype UuidArrayOfHLAbyte16) and the attribute Force at object class has UuidArrayOfHLAbyte16 as datatype. 

Name, datatype and current semantics: "The force that the unit belongs to." should be enough to explain the use of the attribute Fore at object class Unit..

**Comment by bergtwvd** [comment]
So, semantics are to be updated?

**Comment by LennartOlsson** [comment]
Semantics updated in the next version.
"The value is the UUID value of the Force that the unit belongs to."
