### ISSUE TITLE
ORBAT: Force class

### ISSUE THREAD

**Issue by bergtwvd** [MSG134/NETN_FOM#8]
Semantics of this class are unclear. How do instances related to each other?

**Comment by LennartOlsson** [comment]
Yes, could be better explained

**Comment by bergtwvd** [comment]
Proposal?

**Comment by LennartOlsson** [comment]
Semantics updated in the next version.
"Units in a ORBAT belongs to a Force.

Forces have relations to each other which is specified in the attribute Relations.
The relation between forces is defined by HostilityStatusCodeEnum32, e.g. FR (Friendly),  HO (Hostile). 
The relation between Force A and Force B does not have to be the same as the relation between B and A.
The relation may change during a federation execution."
